title: Code Snippets
author: Christian Krudewig
description: Tutorials, stories and insights about software engineering, machine learning and home automation
github_username: chr1st1ank
repository: chr1st1ank/blog
github_repo: blog
url: https://blog.krudewig-online.de
baseurl: ""
# No link to twitter etc.:
social_link: dot
social_username:
lang: en_UK
timezone: Europe/Berlin

# Using https://github.com/broccolini/swiss
remote_theme: broccolini/swiss
ignore_theme_config: true
theme_color: gray

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

feed:
  excerpt_only: true

exclude:
  - ".metals/metals.lock.db"
  - ".config/"
  - "README.md"
  - "code/"
